# Generated by Django 3.2.6 on 2021-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'NA')], default=1),
        ),
    ]
